% -*- mode: Prolog -*-

%% File used to bootstrap builtins_symtab.pl

%% In theory, this could be generated by iterating the bootstrap code
%% to a fixed point.

builtins_version('${VERSION}').

%% TODO: for Python 2: basestring, unicode, long, xrange, buffer (is this all?)
builtins_symtab_primitive(Name, []) :-
    Primitives = [
                  %% 'None', % TODO
                  bool,
                  bytes,
                  complex,
                  dict,
                  float,
                  function,
                  int,
                  list,
                  object,
                  set,
                  str
                 ],
    (  var(Name)
    -> member(Name, Primitives)
    ;  memberchk(Name, Primitives)
    ).

builtins_pairs(Pairs) :-
    bagof(Name-Type, builtins_symtab_primitive(Name, Type), Pairs).

builtins_symtab_modules(symtab{}).

builtins_symtab(Symtab) :-
    builtins_pairs(Pairs),
    dict_pairs(Symtab, symtab, Pairs).


